# Pre-commit hooks configuration
# Chạy `pre-commit install` để kích hoạt hooks

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML
      - id: check-json
        name: Check JSON
      - id: check-toml
        name: Check TOML
      - id: check-xml
        name: Check XML
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: detect-private-key
        name: Detect Private Keys
      - id: check-case-conflict
        name: Check for case conflicts

  # Python-specific hooks
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Format with Black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort imports with isort
        args: ["--profile", "black"]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        name: Security check with Bandit
        args: ['-r', 'app/', '-ll']
        exclude: tests/

  # Local hooks
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: python -m pytest
        language: python
        files: \.(py)$
        pass_filenames: false
        always_run: true

# Global excludes
exclude: |
  (?x)(
    ^venv/|
    ^\.venv/|
    ^__pycache__/|
    \.pyc$|
    ^logs/|
    ^artifacts/|
    ^data/
  )
