import argparse
import json
import logging
import os
import shutil
import sys
import tempfile
from collections import Counter
from pathlib import Path

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import IngestionPipeline directly to test exact logic
from tools.ingest import IngestionPipeline

# Configure Logging
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("pre_flight")


def print_header(title):
    print("\n" + "=" * 60)
    print(f"✈️  PRE-FLIGHT CHECK: {title}")
    print("=" * 60)


def analyze_output(output_dir):
    chunks_file = Path(output_dir) / "chunks" / "chunks.jsonl"

    if not chunks_file.exists():
        print("❌ CRITICAL: No chunks.jsonl generated!")
        return

    chunks = []
    with open(chunks_file, "r", encoding="utf-8") as f:
        for line in f:
            chunks.append(json.loads(line))

    print(f"✅ Total Chunks Generated: {len(chunks)}")

    if not chunks:
        return

    # --- CHECK 1: PAGE METADATA INTEGRITY ---
    print_header("1. PAGE METADATA CHECK (Critical Fix Verify)")
    # Collect all pages found in chunks
    pages_found = []
    for c in chunks:
        page = c["metadata"].get("page")
        if page:
            pages_found.append(page)

    unique_pages = sorted(list(set(pages_found)))
    page_counts = Counter(pages_found)

    print(f"📄 Unique Pages Detected: {unique_pages}")
    print(
        f"📊 Chunks distribution (Sample): Page 1: {page_counts.get(1,0)}, Page 10: {page_counts.get(10,0)}, Page 30: {page_counts.get(30,0)}"
    )

    # Verification Logic
    if len(unique_pages) > 5 and unique_pages[-1] > 5:
        print("✅ SUCCESS: Multi-page metadata detected correctly.")

        # Show a sample from a middle page (e.g., Page 15 or 22 based on your PDF)
        target_page = unique_pages[len(unique_pages) // 2]
        mid_chunk = next(
            (c for c in chunks if c["metadata"].get("page") == target_page), None
        )
        if mid_chunk:
            print(f"\n🔎 [Sample Chunk from Page {target_page}]:")
            print(f"   ID: {mid_chunk['chunk_id']}")
            print(
                f"   Text Snippet: {mid_chunk['text'][:150].replace(chr(10), ' ')}..."
            )
    else:
        print(
            "⚠️ FAIL/WARNING: Only few pages detected. If source > 5 pages, Metadata Fix failed!"
        )

    # --- CHECK 2: TABLE STRUCTURE ---
    print_header("2. TABLE STRUCTURE CHECK")
    chunks_with_tables = [
        c for c in chunks if "metadata" in c and c["metadata"].get("has_tables")
    ]

    if chunks_with_tables:
        print(f"✅ Tables detected in {len(chunks_with_tables)} chunks.")
        # Try to find a chunk with markdown table chars '|' and '---'
        table_chunk = next(
            (c for c in chunks_with_tables if "|" in c["text"] and "---" in c["text"]),
            None,
        )

        if table_chunk:
            print(
                f"\n🔎 [Table Sample from Page {table_chunk['metadata'].get('page')}]:"
            )
            text = table_chunk["text"]
            # Extract just the table part for display
            start = text.find("|")
            end = (
                text.find("\n\n", start)
                if text.find("\n\n", start) != -1
                else len(text)
            )
            print(text[start:end][:500])  # Print first 500 chars of table
            print("\n✅ Markdown Table syntax confirmed.")
        else:
            print("⚠️ Table flag is True but no Markdown syntax found in snippet.")
    else:
        print("ℹ️ No tables detected (Check if PDF actually has tables).")

    # --- CHECK 3: TEXT CLEANING & HEADER/FOOTER ---
    print_header("3. TEXT CLEANING CHECK")
    # Check the first chunk usually contains title info
    first_chunk = chunks[0]
    print(f"\n🔎 [First Chunk - Page {first_chunk['metadata'].get('page')}]:")
    print(f"--- START TEXT ---\n{first_chunk['text'][:300]}\n--- END TEXT ---")

    # Check for footer noise (common issue)
    print("\n🔎 [Checking for Footer Noise in last chunk]:")
    last_chunk = chunks[-1]
    print(f"--- START TEXT ---\n{last_chunk['text'][-300:]}\n--- END TEXT ---")

    # --- CHECK 4: SAFETY QUOTA TAGS PREP ---
    print_header("4. SAFETY QUOTA TAGS PREP")
    # Check if metadata['tags'] exists (generated by TagNormalizer)
    chunks_with_tags = [
        c for c in chunks if "tags" in c["metadata"] and c["metadata"]["tags"]
    ]

    if chunks_with_tags:
        print(f"✅ Tag Enrichment active. Found tags in {len(chunks_with_tags)} chunks.")
        sample = chunks_with_tags[0]
        print(
            f"   Sample Tags (Page {sample['metadata']['page']}): {sample['metadata']['tags']}"
        )
    else:
        print("ℹ️ No Equipment Tags found in text (Normal if PDF is generic manual).")


def run_pre_flight(pdf_path):
    pdf_path = Path(pdf_path).resolve()
    if not pdf_path.exists():
        print(f"❌ File not found: {pdf_path}")
        return

    print(f"🚀 Starting Pre-flight Check for: {pdf_path.name}")

    # Create temp directories
    with tempfile.TemporaryDirectory() as temp_root:
        temp_source = Path(temp_root) / "source"
        temp_output = Path(temp_root) / "output"
        temp_source.mkdir()
        temp_output.mkdir()

        # Copy target PDF to temp source
        shutil.copy(pdf_path, temp_source / pdf_path.name)

        # Initialize Pipeline
        # Using exact same flags as production command:
        # --enable-ocr --ocr-language "vie+eng" --enable-pid-tags --chunk-strategy "hierarchical"
        try:
            print("⚙️  Initializing Ingestion Pipeline...")
            pipeline = IngestionPipeline(
                source_dir=temp_source,
                output_dir=temp_output,
                workers=1,  # Single worker for debug clarity
                enable_ocr=True,
                ocr_language="vie+eng",
                chunk_strategy="hierarchical",
                extract_tables=True,
                enable_pid_tags=True,  # Enable to check CAD gate & tags
            )

            # Run Ingestion
            print("⏳ Processing... (This may take 1-2 minutes for OCR)")
            stats = pipeline.run()

            if stats["failed"] > 0:
                print("❌ Ingestion Failed!")
                # Print quarantine reason
                q_file = temp_output / "quarantine.jsonl"
                if q_file.exists():
                    print("\n📜 Quarantine Log:")
                    print(q_file.read_text(encoding="utf-8"))
            else:
                print("\n✅ Ingestion Pipeline Finished Successfully.")
                analyze_output(temp_output)

        except Exception as e:
            print(f"\n❌ Runtime Error: {e}")
            import traceback

            traceback.print_exc()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Pre-flight Check for PVCFC RAG Ingestion"
    )
    parser.add_argument("pdf_path", help="Path to a single PDF file to test")
    args = parser.parse_args()

    run_pre_flight(args.pdf_path)
